### ISSUE TITLE
what is the prefix

### ISSUE THREAD

**Issue by kessanro** [RubbixCube/discord-music#1]
i need to know the prefix

**Comment by RubbixCube** [comment]
The prefix for the bot is to mention it first. Then the command name

```
@bot#0001 request youtube_url
```

**Comment by kessanro** [comment]
why is it a @ why not something like a prefix like $

**Comment by kessanro** [comment]
and what is the command for @bot join like for it to join the voise channel @RubbixCube

**Comment by RubbixCube** [comment]
Because that's how I designed him in the first place.

To change the bot over to use a prefix command, in `bot.js`, change line `82` and remove the if statement so it just calls the function in `music.js`

```
mods.music.command(e, client, message, msgarray, user, channel, guild, mods, functions);
```  


Then you'll need to change the switch and case statement in `music.js`
Line `15` should look like, `switch(msgarray[0])`
And each case statement should start with the prefix you want...

**Comment by RubbixCube** [comment]
As for joining voice channels, `bot.js` line `57`
```
var musicChannel = guild.voiceChannels.filter(c => c.name == 'General')[0];
```

`'General'` is the name of the voice channel it will auto join, change that with the name of the channel you want it to join instead.
